[package]
name = "rec-wars"
version = "0.1.0"
authors = ["Martin Taibr <taibr.martin@gmail.com>"]
edition = "2018"
description = "A top-down vehicle shooter game playable in the browser"
repository = "https://github.com/martin-t/rec-wars"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
approx = "0.3.2"
console_error_panic_hook = "0.1.6"
hecs = "0.2.14"
js-sys = "0.3.42"
vek = "0.11.2"
wasm-bindgen = "0.2.65"

[dependencies.rand]
version = "0.7.3"
features = ["small_rng"]

[dependencies.web-sys]
version = "0.3.4"
features = [
  "CanvasRenderingContext2d",
  "console",
  "DomMatrix",
  "HtmlImageElement",
  "Performance",
  "Window",
]
