[package]
name = "rec-wars"
version = "0.1.0"
authors = ["Martin Taibr <taibr.martin@gmail.com>"]
edition = "2018"
description = "A top-down vehicle shooter game playable in the browser"
repository = "https://github.com/martin-t/rec-wars"
license = "AGPL-3.0-or-later"

[[bin]]
name = "rec-wars-macroquad"
path = "src/main.rs"

[lib]
# cdylib is for generatig WASM
# Add rlib to run doctests (they don't get run with just cdylib)
# but keep in mind they only work for public items for now:
# https://users.rust-lang.org/t/rustdoc-doctests-and-private-documentation/20955
crate-type = ["cdylib"]

[profile.dev.package."*"]
# Optimize deps but not the rec-wars crate itself (tip from macroquad).
# This seems to slightly improve performance (judging by update avg/max times)
# and shouldn't meaningfully increase incremental compile times because deps only change rarely.
opt-level = 3

[package.metadata.wasm-pack.profile.profiling]
# Rustc optimizations (which make a huge difference) are still enabled but no additional wasm-opt
# Debug symbols are enabled
wasm-opt = false  # see wasm-opt note

[package.metadata.wasm-pack.profile.release]
# All possible optimizations
# No debug symbols (panic messages have line number but stack staces are without function names)
wasm-opt = ["-O3", "--enable-mutable-globals"]  # see wasm-opt note

# wasm-opt note:
# Commit bcf475e5fb (cargo update) causes wasm-opt to fail
# (though the compile itself succeeds and the result seems usable, just without these optimizaions).
# --enable-mutable-globals is a workaround but it seems wasm-opt doesn't help perf that much
# while somewhat slowing down compiling.
# https://github.com/rustwasm/wasm-pack/issues/886

[dependencies]
approx = "0.4.0"
console_error_panic_hook = "0.1.6"
enumn = "0.1.3"
fnv = "1.0.7"
js-sys = "0.3.42"
macroquad = "0.3.0-alpha.14"
rand_distr = "0.4.0"
thunderdome = "0.4.0"
vek = "0.13.0"
wasm-bindgen = "0.2.65"

[dependencies.getrandom]
version = "0.2.0"
features = ["js"]

[dependencies.image]
# Dependency of macroquad with added "bmp" feature
version = "0.22"
default-features = false
features = ["png_codec", "tga", "bmp"]

[dependencies.rand]
version = "0.8.0"
features = ["small_rng"]

[dependencies.web-sys]
version = "0.3.4"
features = [
  "CanvasRenderingContext2d",
  "console",
  "DomMatrix",
  "HtmlCanvasElement",
  "HtmlImageElement",
  "Performance",
  "Window",
]

[dev-dependencies]
walkdir = "2.3.1"
