[package]
name = "rec-wars"
version = "0.1.0"
authors = ["Martin Taibr <taibr.martin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
# wasm-pack apparently uses the release profile
debug = true  # this doesn't seem to help with stack traces in WASM

[dependencies]
approx = "0.3.2"
console_error_panic_hook = "0.1.6"
js-sys = "0.3.42"
vek = "0.11.2"
wasm-bindgen = "0.2.65"

[dependencies.rand]
version = "0.7.3"
features = ["small_rng"]

[dependencies.web-sys]
version = "0.3.4"
features = [
  "CanvasRenderingContext2d",
  "console",
  "DomMatrix",
  "HtmlImageElement",
]
