name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 15:00 UTC on Fri 
    - cron: "0 15 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install libx11-dev libxi-dev libgl1-mesa-dev
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --features mq
      - name: Run tests
        run: cargo test --verbose

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      # https://github.com/rust-random/getrandom/issues/175
      - run: cargo audit --deny warnings --ignore RUSTSEC-2020-0056
